production_url: "http://www.jsonq.org"

widgets :
    analytics :
        use : google
        tracking_id : 'UA-54191340-1'
    google_prettify :
      use : default
      linenums : true

"bin":
    use: "ignore"

"theme-jsonq":
    use: "ignore"

"theme-jsonq-dark":
    use: "theme"
